<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-android</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefineConstants>$(DefineConstants);ANDROID</DefineConstants>
    <SupportedOSPlatformVersion>21.0</SupportedOSPlatformVersion>
    <Version>2.0.2</Version>

  </PropertyGroup>


  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  
  

</Project>
